site:
    title: Hyper.sh
    subtitle: Clusterless Docker Hosting
    logo: https://www.hyper.sh/logo/logo_dark.svg
    limit: 10
    theme: theme
    lang: en
    url: "https://blog.hyper.sh/"
    comment: hyperhq
    # link: "{title}.html"
    # root: "/blog"

authors:
    hyper:
        name: The Hyper.sh Team
        intro: Clusterless Docker Hosting
        avatar: https://www.hyper.sh/logo/logo_single_dark.svg
    xu:
        name: Xu Wang
        intro: Founder
        avatar: -/images/xu.jpg
    tibo:
        name: Thibault Bronchain
        intro: Developers Ambassador
        avatar: -/images/tibo.jpg

build:
    port: 8000
    # Copied files to public folder when build
    copy:
        - "source/images"
    # Excuted command when use 'ink publish'
    publish: |
        git add . -A
        git commit -m "update"
        git push origin
