site:
    title: Hyper
    subtitle: Make VM run like Container
    logo: -/images/logo.png
    limit: 10
    theme: theme
    disqus: hyperhq
    root: /blog

authors:
    me:
        name: Hyper
        intro: Make VM run like Container
        avatar: -/images/avatar.png
    xu:
        name: Xu Wang
        intro: Founder
        avatar: -/images/xu.jpg
    tibo:
        name: Thibault Bronchain
        intro: Developers Ambassador
        avatar: -/images/tibo.jpg

build:
    port: 8000
    copy:
        # Copied files to public folder when build
        - theme/css
        - theme/js
        - theme/favicon.ico
        - theme/robots.txt
        - source/images
    publish: |
        # Excuted command when use 'ink publish'
        git add . -A
        git commit -m "update"
        git push origin
